### ISSUE TITLE
TODO Before Public

### ISSUE THREAD

**Issue by haesbaert** [haesbaert/oslo#1]
- [x] Stop always kicking 6f904f9
- [x] Go over minor XXX 747e5b561a2996b649503a7b74b333fb4ed8de43
- [x] Switch/Bless/Curse thing d528a7b29968d7774ca0151f047fe29d684ba298 545b194686fcab41b2a1efdd5e3835e2b2b122d2 a5ca245e6c645c14aef888a7c6ae05d0f4e63c09 e99f11db42cf040eb6ed14850f3a85acf110e925
- [x] Split modules 67cf65fd869d9c564b7e0bc114ce0f25aed45861 968a53f3818f5aedbefa9e40a899a6d5acd711af 20e1029ae97f5cd751b5696938aa865f99c4d866 541ecfadbe726c68006c5bec0d6774f20a111975 db7f3c9c1e357175c0a6373c4bf017612cdd9e9a 6fad70776ecd7d0d7f2750a234d389aa7fb7b535 99af50bcae547dc8d4e41391648ab5af731e5d97
- [x] Write interfaces 
  - [x] Ownership 8b53122bc3072cfecbea9a9170d3d0fa4f546049 
  - [x] Promise e22e307680d1b796842c05906ca7794bf9939e91 
  - [x] Spinlock 3e8d9a667e197db124e813324d4bd3c306b48032
  - [x] Condition 318c800d172fecdda9c02c82ecbf7551207ced34
  - [x] Barrier 0adc9afdaffb5138f9aa8c89faf5d72ad7fed637
  - [x] Odomain 4c313b27e0d9cf50a851c832f9c64de41e830311
  - [x] Spsc f5827a4abccd90cb1173d484034ce9621746fcc1
  - [x] Task 8c53ffb0ee21480c16136ebf94c80d59ffee6175 6ab07b7d6e2e08b056c9a9ac2146cd1d376762c1
  - [x] Token 29e28bafa439fd53b5944d8a525c66e67d901d9c
  - [x] Boundq cd85f58f6f2b131a26db83427a1fa1848f79f9b0
  - [x] Io 540708500ac3b6aaabb4ff21bbc9c5356f78ee42
- [x] Channel/Stream implementation a8007a9cf572512bd4e90ad9870a93caa5f27595
- [x] Write introduction
- [x] Write README
- [x] Write tutorial based on echo cd9fcdc32eae592ab986cd622750b7dd83ffc996
- [x] Write some subjective stuff about the philosophy/idea (Covered in Task.philosophy).
- [x] Greed mechanism 66bc36a405e2dd9a970800ca8562a28a30eed6b6
- [x] Remove main_finished hack 8bb1238ba5f1977addf376780da38a8cfaf4ee54
- [x] Decide on Task.(async vs async_p vs async_c vs parallell vs concurrent) 9d30ab6faff348bb393bb3e7e414395f5991bbba
- [x] ~~Fixup backtrace for task exceptions~~ Not sure how to do it since we don't have nested effect handlers, need more time.
- [x] Make timeouts O(1) 4bee1a7381fc928ae0c916b33bee8db0342b502d
- [x] ~~Make Local vs Remote optimization so local tasks will be zero atomic ops~~ Couldn't justify the complexity, saw no improvement in micro benchmarks.
- [x] Make non atomic tid allocator for 64 bits, keep current for 32 bits 16f447b688463c963e0c7e77281df613556f218d
